CHANGELOG.md
libcove/lib/common.py
setup.py

This is required for
https://github.com/OpenDataServices/cove/issues/1117

Put validator type into the context

---

CHANGELOG.md
libcove/lib/common.py
setup.py

This is the BODS specific oneOf work from this PR https://github.com/OpenDataServices/lib-cove/pull/8
Since this is BODS specific, we should be able to merge/release this without needing to consult other standards.

Improve validation error messages for oneOf

---

.gitignore
CHANGELOG.md
libcove/lib/common.py

This will allow different CoVEs to write their own validation messages. We want this for BODS first of all.
Context: https://github.com/openownership/cove-bods/issues/16#issuecomment-478426310

Put more data into the error JSON returned, when grouping validation errors

---

libcove/lib/common.py

- Make schema_url a required parameter as it is required by
CustomJsonrefLoader's get_remote_json
- Use urllib to manipulate the uri given to get_remote_json
rather than string manipulation of the uri. This should make it more
robust against rogue strings.

libcove common Tidy up of CustomJsonrefLoader

---

CHANGELOG.md
libcove/lib/converters.py
setup.py
tests/lib/test_converters.py

part of https://github.com/OpenDataServices/cove/issues/1208
Allows the organisation-identifier to be present when converting IATI XML data.
`root_id` is passed as an optional parameter to `convert_json`

add root_id as an optional parameter to convert_json

---

.isort.cfg
.travis.yml
libcove/config.py
libcove/lib/common.py
libcove/lib/converters.py
libcove/lib/exceptions.py
libcove/lib/tools.py
requirements_dev.txt
setup.cfg
setup.py
tests/lib/test_common.py
tests/lib/test_converters.py
tests/lib/test_tools.py

As discussed at the dev retreat - format the Python code in this repository with black (general Python code formatter) and isort (sorts imports).
A downside is black only works with Python3.6, although it will make changes that are compatible with earlier versions (including Python 2). I have added if statements to the Travis config to deal with this.
flake8 is still used, but without any style checking.
I'd quite like to get this merged promptly if possible, so that I can try it out for changes to this repo.

Format code with black and isort

---

CHANGELOG.md
libcove/lib/common.py
tests/lib/fixtures/common/1-0/record-package-schema.json
tests/lib/fixtures/common/1-0/records_invalid_releases.json
tests/lib/fixtures/common/1-0/release-schema.json
tests/lib/test_common.py

https://github.com/OpenDataServices/cove/issues/895#issuecomment-558721218

Extend new oneOf validation messages to OCDS 1.0 files

---

CHANGELOG.md
setup.py

These optional dependencies of `jsonschema` are required to validate URIs and date-times correctly.
https://github.com/openownership/lib-cove-bods/pull/54#issuecomment-585303356

Depend on rfc3987 and strict-rfc3339 to validate formats correctly

---

libcove/lib/common.py
tests/lib/test_common.py

I assume this has changed between different versions of black, because this didn't block merging.

lint: Run black

---

CHANGELOG.md
libcove/lib/common.py
setup.py
tests/lib/test_common.py

This cuts test time down on my machine for lib-cove-ocds from 40s to 6s (paired with corresponding changes in that repo).
This will also improve performance in Kingfisher Process, so that jsonschema and jsonref aren't repeatedly requesting URLs.

Have CustomRefResolver and CustomJsonrefLoader respect cache_all_requests

---

CHANGELOG.md
libcove/lib/common.py
setup.py

Fixes recent Sentry errors in cove-ocds and kingfisher-process.
Occurs because an MTender extension does:
```json
"ValueDifference": {
"title": "",
"description": "",
"type": "object",
"properties": {
"value": "",
"unit": {
"$ref": "#/definitions/Unit"
}
},
"extension": "eAuction"
},
```
`value` can't be a string. It must be a JSON Schema.
Problem is in https://raw.githubusercontent.com/eOCDS-Extensions/eOCDS-eAuction/master/release-schema.json
cc @duncandewhurst

common: Log warning for invalid JSON Schema in which "properties" values aren't JSON Schema

---

.github/workflows/lint.yml
libcove/lib/common.py
requirements_dev.txt
tests/lib/test_common.py

Use a create and rename strategy instead of locking the file here.
Fixes Issue #53
Add comprehensive tests for the function.

Remove dependency on fcntl (improves Windows support)

---

.github/workflows/lint.yml
.github/workflows/test.yml
libcove/lib/tools.py
requirements_dev.txt
tests/lib/test_tools.py

run latest version of black against the code.

lint: Move black into requirements, drop Python 3.5 from CI,

---

tests/lib/test_common.py

This is the test relating to this PR:
https://github.com/OpenDataServices/lib-cove/pull/71/files

tests: "properties" values that aren't JSON schema don't cause exception

---

.github/workflows/lint.yml
requirements_dev.txt
requirements_dev_lint.txt
tests/lib/test_common.py

We just saw lint runs fail due to an upgrade in black, not a code change

black: Lock to version to ensure stable lint runs

---

CHANGELOG.md
libcove/lib/common.py
tests/lib/test_common.py

fixes #101
replaces #102
You can undo the change to common.py to see one of the new tests fail.

fix: Numeric "id" values no longer cause an exception while yielding a validation error about non-unique IDs

---

tests/lib/fixtures/common/release-package-schema.json
tests/lib/test_common.py

This indirectly tests process_codelists on the SchemaJsonMixin, which was added in:
https://github.com/OpenDataServices/lib-cove/pull/109/

tests: Test get_additional_codelist_values

---

CHANGELOG.md
libcove/lib/common.py

From https://github.com/OpenDataServices/lib-cove/pull/127

Restore jsonschema's type validator, as its performance has improved in recent Python versions

---

CHANGELOG.md
libcove/lib/common.py

This accepts lib-cove's JSON Schema draft 4 validator class and its format checker, and returns a validator instance.

Allow SchemaJsonMixin classes to define a validator method

---

CHANGELOG.md
libcove/lib/common.py
tests/lib/fixtures/common/schema_with_oneof_codelists.json
tests/lib/test_common.py

Like OCDS record packages
https://github.com/OpenDataServices/lib-cove/pull/125 https://github.com/open-contracting/lib-cove-ocds/issues/106

Calculate additional codelist values for schema using anyOf

---

CHANGELOG.md
libcove/lib/common.py
tests/lib/fixtures/common/schema_nullable_object_and_array.json
tests/lib/test_common.py

For example, OCDS `parties/details` is nullable, and additional codes for `parties/details/scale` were unreported.
https://github.com/OpenDataServices/lib-cove/pull/131

Descend into nullable objects and arrays

---

CHANGELOG.md
libcove/lib/common.py
setup.py
tests/lib/test_common.py

https://github.com/OpenDataServices/lib-cove/pull/123

Jsonschema 4.18+ is now required

---

.github/workflows/integration.yml
libcove/lib/common.py

If `instance` has no ID fields, `uniq(instance)` isn't called once, but as many times as the length of `instance`.
Original commit d28dd0129690df972c46a917c13e2f94764f5225

fix: unique_ids has exponential running time if no ID fields
